# Aranya take-home cluster inventory
#
# 3-node HA cluster: each node is control plane + worker + etcd (stacked).
# - ansible_host = the IP Ansible SSHes to (public, since my Mac is off-VPC)
# - ip           = the IP the K8s components bind to internally (private VPC, eth1)
# - access_ip    = the IP other K8s components use to reach this node (private)

[all:vars]
ansible_user=root
ansible_ssh_private_key_file=/Users/Nikita/.ssh/aranya_candidate_key
ansible_python_interpreter=/usr/bin/python3

[kube_control_plane]
node1 ansible_host=138.68.244.183  ip=10.120.0.8   access_ip=10.120.0.8   etcd_member_name=etcd1
node2 ansible_host=167.172.197.138 ip=10.120.0.9   access_ip=10.120.0.9   etcd_member_name=etcd2
node3 ansible_host=165.227.57.127  ip=10.120.0.10  access_ip=10.120.0.10  etcd_member_name=etcd3

[etcd:children]
kube_control_plane

[kube_node]
node1
node2
node3

[k8s_cluster:children]
kube_control_plane
kube_node
